import subprocess
import os
import time
import tempfile
import shutil
import logging

logger = logging.getLogger("slimcraft")


def _run(cmd, check=True):
    """Run a shell command and return stdout."""
    result = subprocess.run(
        cmd, capture_output=True, text=True, check=check
    )
    if result.returncode != 0 and not check:
        return ""
    return result.stdout.strip()


def _is_git_repo():
    """Check if CWD is inside a git repo."""
    return _run(["git", "rev-parse", "--git-dir"], check=False) != ""


def _gh_authenticated():
    """Check if gh CLI is authenticated."""
    out = _run(["gh", "auth", "status"], check=False)
    return "Logged in" in out


def _git_root():
    """Get the root of the git repo."""
    return _run(["git", "rev-parse", "--show-toplevel"])


def _rel_path(absolute_path):
    """Convert absolute path to repo-relative path."""
    root = _git_root()
    if absolute_path.startswith(root):
        return os.path.relpath(absolute_path, root)
    return absolute_path


def _dirty_warning():
    """Warn if working tree has uncommitted changes."""
    status = _run(["git", "status", "--porcelain"], check=False)
    return bool(status)


def open_pr_with_diff(original_path, rewritten_content, rationale):
    """
    Create a GitHub PR using gh CLI with the rewritten Dockerfile.
    Returns True on success, False on failure.
    """
    if not _is_git_repo():
        print("Not a git repository. PR creation requires a git repo.")
        return False

    if not _gh_authenticated():
        print(
            "GitHub CLI (gh) not authenticated. "
            "Run 'gh auth login' first."
        )
        return False

    if _dirty_warning():
        print(
            "Warning: You have uncommitted changes. "
            "PR will include all current changes."
        )

    with open(original_path) as f:
        original_content = f.read()

    if rewritten_content == original_content:
        print("No changes to commit. Dockerfile content is identical.")
        return False

    branch = f"slimcraft/harden-{int(time.time())}"
    rel = _rel_path(os.path.abspath(original_path))
    title = f"chore: harden {rel}"
    body = (
        f"## Rationale\n\n{rationale}\n\n"
        "---\n*Generated by slimcraft*"
    )

    try:
        _run(["git", "checkout", "-b", branch])
        # Write to temp file first, then atomically replace
        fd, tmp = tempfile.mkstemp(dir=os.path.dirname(original_path))
        try:
            with os.fdopen(fd, 'w') as f:
                f.write(rewritten_content)
            shutil.move(tmp, original_path)
        except Exception:
            os.unlink(tmp)
            raise
        _run(["git", "add", original_path])
        _run(["git", "commit", "-m", title])
        _run(["git", "push", "-u", "origin", branch])
        pr_url = _run(["gh", "pr", "create", "--title", title, "--body", body])
        print(f"PR created: {pr_url}")
        _run(["git", "checkout", "-"])
        return True
    except Exception as e:
        logger.exception("PR creation failed")
        # Restore original content
        with open(original_path, 'w') as f:
            f.write(original_content)
        _run(["git", "checkout", "-"], check=False)
        _run(["git", "branch", "-D", branch], check=False)
        print(f"PR creation failed: {e}")
        return False
